#! /bin/bash

VIEWER_HOME=$(dirname $0)

cd $VIEWER_HOME && groovy -cp build/libs/modica-0.1.war \
        scripts/modicaViewerBootstrap.groovy $@

#TODO bundle groovy runtime and execute: 
#cd $VIEWER_HOME && java -jar groovy-all*.jar scripts/modicaViewerBootstrap.groovy $@
